{
 "title": "House Price Prediction Dashboard",
 "tags": [
  "machine-learning",
  "fastapi"
 ],
 "refresh": "5s",
 "panels": [
  {
   "title": "API Request Latency (p95)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(app_request_latency_seconds_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Prediction Engine Latency (p95)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(prediction_latency_seconds_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Failed Requests (Last 5m)",
   "type": "stat",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 5 },
   "targets": [
    {
     "expr": "sum(rate(app_requests_failed_total[5m]))"
    }
   ]
  },
  {
   "title": "Total API Requests (Last 5m)",
   "type": "stat",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 5 },
   "targets": [
    {
     "expr": "sum(rate(app_request_latency_seconds_count[5m]))"
    }
   ]
  }
 ]
}